name: fourmolu
on:
  - push
  - pull_request
jobs:
  linux:
    name: Fourmolu Format Check
    runs-on: ubuntu-18.04
    container:
      image: buildpack-deps:xenial
    steps:
      - name: apt
        run: |
          apt-get update
          apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git software-properties-common
          apt-add-repository -y 'ppa:hvr/ghc'
          apt-get update
          apt-get install -y ghc-8.10.4 cabal-install-3.4
      - name: Set PATH and environment variables
        run: |
          echo "$HOME/.cabal/bin" >> $GITHUB_PATH
          echo "LANG=C.UTF-8" >> $GITHUB_ENV
          echo "CABAL_DIR=$HOME/.cabal" >> $GITHUB_ENV
          echo "CABAL_CONFIG=$HOME/.cabal/config" >> $GITHUB_ENV
          HCDIR=$(echo "/opt/ghc-8.10.4" | sed 's/-/\//')
          HCNAME=ghc
          HC=$HCDIR/bin/$HCNAME
          echo "HC=$HC" >> $GITHUB_ENV
          echo "HCPKG=$HCDIR/bin/$HCNAME-pkg" >> $GITHUB_ENV
          echo "HADDOCK=$HCDIR/bin/haddock" >> $GITHUB_ENV
          echo "CABAL=/opt/cabal/3.4/bin/cabal -vnormal+nowrap" >> $GITHUB_ENV
          HCNUMVER=$(${HC} --numeric-version|perl -ne '/^(\d+)\.(\d+)\.(\d+)(\.(\d+))?$/; print(10000 * $1 + 100 * $2 + ($3 == 0 ? $5 != 1 : $3))')
          echo "HCNUMVER=$HCNUMVER" >> $GITHUB_ENV
          echo "ARG_TESTS=--enable-tests" >> $GITHUB_ENV
          echo "ARG_BENCH=--enable-benchmarks" >> $GITHUB_ENV
          echo "HEADHACKAGE=false" >> $GITHUB_ENV
          echo "ARG_COMPILER=--$HCNAME --with-compiler=$HC" >> $GITHUB_ENV
          echo "GHCJSARITH=0" >> $GITHUB_ENV
      - name: env
        run: |
          env
      - name: write cabal config
        run: |
          mkdir -p $CABAL_DIR
          cat >> $CABAL_CONFIG <<EOF
          remote-build-reporting: anonymous
          write-ghc-environment-files: never
          remote-repo-cache: $CABAL_DIR/packages
          logs-dir:          $CABAL_DIR/logs
          world-file:        $CABAL_DIR/world
          extra-prog-path:   $CABAL_DIR/bin
          symlink-bindir:    $CABAL_DIR/bin
          installdir:        $CABAL_DIR/bin
          build-summary:     $CABAL_DIR/logs/build.log
          store-dir:         $CABAL_DIR/store
          install-dirs user
            prefix: $CABAL_DIR
          repository hackage.haskell.org
            url: http://hackage.haskell.org/
          EOF
          cat $CABAL_CONFIG
      - name: versions
        run: |
          $HC --version || true
          $HC --print-project-git-commit-id || true
          $CABAL --version || true
      - name: update cabal index
        run: |
          $CABAL v2-update -v
      - name: install fourmolu
        run: |
          $CABAL install $ARG_COMPILER fourmolu
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: source
      - name: check syntax
        run: |
          fourmolu -c $(find source -name '*.hs')
